#!/bin/sh

set -e
set -u

WORK_DIR=$(pwd)
ROOT_DIR=$(dirname "$0")

test -n "$ROOT_DIR"
cd "$ROOT_DIR"

mkdir -p m4
mkdir -p build-aux

aclocal -I .
automake --add-missing --copy --foreign
autoconf

cd "$WORK_DIR"
"$ROOT_DIR"/configure "$@"
